name: Greetings or message to the user when they find a issue or when they make their first pull request.

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Well done, you found very first issue'
        pr-message: 'Congratulations you made your very first pull request. Keep it up '
       
